// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/create-promo": {
            "post": {
                "description": "Create a new promo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create new promo",
                "parameters": [
                    {
                        "description": "Promo Details",
                        "name": "promo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    }
                }
            }
        },
        "/delete-promo/{id}": {
            "delete": {
                "description": "Delete promo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete promo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Promo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    }
                }
            }
        },
        "/get-promos": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "List all promos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    }
                }
            }
        },
        "/update-promo": {
            "put": {
                "description": "Update a new promo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update new promo",
                "parameters": [
                    {
                        "description": "Promo Details",
                        "name": "promo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Promo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Promo": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "finishDate": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "promoCode": {
                    "type": "string"
                },
                "promoDescription": {
                    "type": "string"
                },
                "promoDiscount": {
                    "type": "string"
                },
                "promoPictureURL": {
                    "type": "string"
                },
                "promoType": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
